# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
env:
  ALLURE_VERSION: "2.10.0"
  SUREFIRE_ARGS_BDD: "--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED  --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types:
      - webhook


jobs:
  build:
    name: Tests on JDK
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        java: [ 8, 11, 13, 14, 15, 17, 18 ]  # doesn't work on 16

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          distribution: 'zulu'
          cache: 'maven'

      - name: Build with Maven
        id: build
        run: mvn install -DskipTests -ntp

      - name: Set parameters for AspectJ
        id: aspect_j_params
        if: ${{ matrix.java > 15 }}
        run: |
          echo "ASPECT_ARGS_BDD=-Daspectj.args="\"$SUREFIRE_ARGS_BDD\" >> $GITHUB_ENV

      - name: Set parameters for AspectJ
        id: aspect_j_params_empty
        if: ${{ matrix.java < 16 }}
        run: |
          echo "ASPECT_ARGS_BDD=-Daspectj.args=''" >> $GITHUB_ENV

      - name: Tests
        id: ftests
        timeout-minutes: 10
        run: mvn test -ntp ${{ env.ASPECT_ARGS_BDD }} --fail-at-end

      - name: Check tests are passed
        if: ${{ steps.ftests.outcome != 'success' }}
        run: |
          echo Tests result: ${{ steps.ftests.outcome }}
          exit 1